{"variants":[{"paths":["\/documentation\/foundationextras\/tryfrom\/failure"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure\/conversionFailure(message:)"]},{"identifiers":["doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure\/Equatable-Implementations","doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure\/Error-Implementations"],"generated":true,"title":"Default Implementations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"Failure"}],"roleHeading":"Enumeration","modules":[{"name":"FoundationExtras"}],"title":"TryFrom.Failure","role":"symbol","externalID":"s:16FoundationExtras7TryFromV7FailureO","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Failure"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure"},"abstract":[{"text":"A universal error type that is available to all custom implementations of the TryFrom trait.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Failure","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/FoundationExtras\/documentation\/FoundationExtras","doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom"]]},"relationshipsSections":[{"identifiers":["doc:\/\/FoundationExtras\/SQ","doc:\/\/FoundationExtras\/s5ErrorP","doc:\/\/FoundationExtras\/s8SendableP"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"references":{"doc://FoundationExtras/SQ":{"identifier":"doc:\/\/FoundationExtras\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://FoundationExtras/documentation/FoundationExtras/TryFrom/Failure/Equatable-Implementations":{"kind":"article","type":"topic","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure\/Equatable-Implementations","role":"collectionGroup","url":"\/documentation\/foundationextras\/tryfrom\/failure\/equatable-implementations"},"doc://FoundationExtras/s8SendableP":{"identifier":"doc:\/\/FoundationExtras\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://FoundationExtras/documentation/FoundationExtras/TryFrom/Failure":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"Failure","kind":"identifier"}],"identifier":"doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure","title":"TryFrom.Failure","abstract":[{"text":"A universal error type that is available to all custom implementations of the TryFrom trait.","type":"text"}],"role":"symbol","url":"\/documentation\/foundationextras\/tryfrom\/failure","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Failure"}]},"doc://FoundationExtras/documentation/FoundationExtras":{"identifier":"doc:\/\/FoundationExtras\/documentation\/FoundationExtras","title":"FoundationExtras","url":"\/documentation\/foundationextras","type":"topic","abstract":[{"type":"text","text":"Useful extensions to the Foundation framework."}],"kind":"symbol","role":"collection"},"doc://FoundationExtras/s5ErrorP":{"identifier":"doc:\/\/FoundationExtras\/s5ErrorP","title":"Swift.Error","type":"unresolvable"},"doc://FoundationExtras/documentation/FoundationExtras/TryFrom":{"kind":"symbol","identifier":"doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TryFrom"}],"type":"topic","role":"symbol","title":"TryFrom","url":"\/documentation\/foundationextras\/tryfrom","navigatorTitle":[{"kind":"identifier","text":"TryFrom"}],"abstract":[{"type":"text","text":"Protocols in Swift are limited, period. Protocols cannot be implemented multiple times with"},{"type":"text","text":" "},{"type":"text","text":"different implementations!"}]},"doc://FoundationExtras/documentation/FoundationExtras/TryFrom/Failure/conversionFailure(message:)":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"conversionFailure","kind":"identifier"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"type":"topic","abstract":[],"title":"TryFrom.Failure.conversionFailure(message:)","role":"symbol","identifier":"doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure\/conversionFailure(message:)","kind":"symbol","url":"\/documentation\/foundationextras\/tryfrom\/failure\/conversionfailure(message:)"},"doc://FoundationExtras/documentation/FoundationExtras/TryFrom/Failure/Error-Implementations":{"identifier":"doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure\/Error-Implementations","type":"topic","kind":"article","url":"\/documentation\/foundationextras\/tryfrom\/failure\/error-implementations","role":"collectionGroup","title":"Error Implementations","abstract":[]}}}